## KinD Helpers
export KIND_INSTALL_DOCKER_REGISTRY?=1

## Create k3d local cluster
k3d/create:
	@@${BUILD_HARNESS_EXTENSIONS_PATH}/modules/k3d/k3d.sh create

## Delete k3d local cluster
k3d/delete:
	@@${BUILD_HARNESS_EXTENSIONS_PATH}/modules/k3d/k3d.sh delete

