## Kubecfg helpers
KUBECFG_TARGETS ?= $(patsubst %,k8s/kubecfg/validate/%,$(shell find rendered/ -type d -name manifests 2>/dev/null))

## Validate manifests
.PHONY: k8s/kubecfg/validate
k8s/kubecfg/validate: $(KUBECFG_TARGETS)

.PHONY: $(KUBECFG_TARGETS)
$(KUBECFG_TARGETS):
	kubecfg validate $(subst k8s/kubecfg/validate/,,$@)/*.yaml
