## KinD Helpers
export KIND_INSTALL_DOCKER_REGISTRY?=1

kind/create:
	@@${BUILD_HARNESS_EXTENSIONS_PATH}/bin/kind.sh create

## Delete KinD local cluster
kind/delete:
	@@${BUILD_HARNESS_EXTENSIONS_PATH}/bin/kind.sh delete

