## KinD Helpers

## Start KinD local cluster
kind/create:
	@@${BUILD_HARNESS_EXTENSIONS_PATH}/bin/kind.sh create

## Delete KinD local cluster
kind/delete:
	@@${BUILD_HARNESS_EXTENSIONS_PATH}/bin/kind.sh delete

