## python isort helpers

# Run as python module so it supports virtual environment managers
ISORT ?= $(PYTHON) -m isort
ISORT_FLAGS ?= --profile black
# Use black profile

## Check python imports using isort
python/isort/check:
	@$(MAKE) python/lint/announce/isort
	@$(ISORT) $(ISORT_FLAGS) --check-only $(PYTHON_LINT_TARGETS) --diff

## Fix python imports using isort
python/isort:
	@$(ISORT) $(ISORT_FLAGS) $(PYTHON_LINT_TARGETS)
