## python black helpers

# Run as python module so it supports virtual environment managers
BLACK ?= $(PYTHON) -m black

## Check python files using black
python/black/check:
	@$(MAKE) python/lint/announce/black
	@$(BLACK) --check $(PYTHON_LINT_TARGETS)

## Reformat python files using black
python/black:
	@$(BLACK) $(PYTHON_LINT_TARGETS)
