# Install hashicorp sentinel functions
.PHONY: sentinel/hashicorp-functions
sentinel/hashicorp-functions:
	if [ ! -d "./sentinel-extensions" ]; then git submodule add https://github.com/hashicorp/terraform-sentinel-policies.git sentinel-extensions; fi
