name: asdf
on: [pull_request]
jobs:
  asdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: combine tool-verions
        run: cat modules/satoshi/tf-tool-versions modules/satoshi/k8s-tool-versions > .tool-versions
        shell: bash
      - name: setup
        uses: asdf-vm/actions/setup@v2
      - name: plugins
        run: | # plugins which require a specific install path need to be added here
          asdf plugin add amtool https://gitlab.com/gitlab-com/gl-infra/asdf-promtool.git
          asdf plugin add go-jsonnet https://github.com/sirikon/asdf-go-jsonnet.git
          asdf plugin add kyverno-cli https://github.com/hobaen/asdf-kyverno-cli.git
      - name: install
        uses: asdf-vm/actions/install@v2