name: asdf
on:
  push:
    branches:
      - test-asdf-ci
jobs:
  asdf:
    runs-on: ubuntu-latest
    steps:
      - name: combine tool-verions
        runs: ./asdf_file_builder.sh
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: setup
        uses: asdf-vm/actions/setup@v2
      - name: install
        uses: asdf-vm/actions/install@v2