name: mise
on: [pull_request]
jobs:
  mise:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: combine tool-versions
        run: cat modules/satoshi/tf-tool-versions modules/satoshi/k8s-tool-versions > .tool-versions
        shell: bash
      - name: setup mise
        uses: jdx/mise-action@v2
        with:
          install: false
      - name: plugins setup
        run: grep -E "^#asdf:" '.tool-versions' | cut -d':' -f2- | sed 's/plugin add/plugins install/' | tr '\n' '\0' | xargs -0 -n1 -Icmd -- sh -c 'mise cmd' || true
      - name: install
        run: mise install --yes
