name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/30 * * * *'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      # - name: Setup node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      - name: Renovate
        uses: renovatebot/github-action@53bdcc4ec92f28e5023ac92356ea8bb45f8b807d # v43.0.15
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate-config.js
